name = "scrpall"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Free plan mein CPU time limit
# Agar timeout ho to yeh badhao (paid plan mein)
# [limits]
# cpu_ms = 50

# Custom domain (optional)
# [[routes]]
# pattern = "api.yourdomain.com/*"
# zone_name = "yourdomain.com"
